### ISSUE TITLE
Detect directory as path for downloads in CLI

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/libstorj#197]
OS: windows 10
```
C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin>storj download-file 727899d0b847fe1c2edde6a5 e85dc67b2ec12868ddd900b5 C:\temp
Warning: File already exists at path [C:\temp].
Would you like to overwrite [C:\temp]: [y/n]
```

**Comment by MeijeSibbel** [comment]
```
C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin>storj download-file 727899d0b847fe1c2edde6a5 e85dc67b2ec12868ddd900b5 C:\temp
Warning: File already exists at path [C:\temp].
Would you like to overwrite [C:\temp]: [y/n] y
Unable to open C:\temp: Permission denied

C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin>
```

**Comment by MeijeSibbel** [comment]
```
C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin>storj download-file 727899d0b847fe1c2edde6a5 e85dc67b2ec12868ddd900b5 D:\
Warning: File already exists at path [D:\].
Would you like to overwrite [D:\]: [y/n] y
Unable to open D:\: No such file or directory
```

**Comment by MeijeSibbel** [comment]
```
C:\Users\Dani Marion\Desktop\storj-1.0.0-beta1\bin>storj download-file 727899d0b847fe1c2edde6a5 e85dc67b2ec12868ddd900b5  D:\download
Warning: File already exists at path [D:\download].
Would you like to overwrite [D:\download]: [y/n] y
Unable to open D:\download: Permission denied
```

**Comment by MeijeSibbel** [comment]
Issue was resolved when running cmd as adminstrator

**Comment by aleitner** [comment]
uh oh. You have to specify a file name. It's turning these folders into files

**Comment by MeijeSibbel** [comment]
ahh, with the old core-CLI we could just specify a directory and it would just save the file with the correct file name in the directory, i will try again

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
