### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by braydonf** [storj/libstorj#219]
There are still several manual processes for making a release:
- Building set of dependencies for each host
- Running `make`, `make clean`, `./configure` and `make install` for each host using supplied configurations in the readme.
- Packaging up in `tar.giz` and `zip` files for each host, and moving to a new directory
- Running `sha256sum * > SHA256SUMS` and `gpg --clearsign SHA256SUMS`

This can lead into doing deterministic builds using [gitian](https://github.com/devrandom/gitian-builder) and/or [debian reproducible builds](https://wiki.debian.org/ReproducibleBuilds).

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
