### ISSUE TITLE
Include `.so` `.dylib` and `.dll` files in releases

### ISSUE THREAD

**Issue by braydonf** [storj/libstorj#228]
Include shared libraries in release, in addition to static archive.

**Comment by braydonf** [comment]
This is a priority for building out wrappers and bindings in other languages.

**Comment by BlackDuck888** [comment]
it would be fine if those shared libs are already static, that other dependencies are note need. this will it make much more easy for others to step in.

**Comment by braydonf** [comment]
So I was able to get `.so` to compile from statically compiled dependencies using `--with-pic` in https://github.com/Storj/libstorj/pull/359

Still taking a look at compiling `.dll` and started an example at https://github.com/braydonf/autotools-boilerplate and have the `.dll` compiling there, so just need to connect the two.

**Comment by braydonf** [comment]
Branch with some work on this is at https://github.com/braydonf/libstorj/tree/shared  with PR https://github.com/Storj/libstorj/pull/359

**Comment by braydonf** [comment]
Okay most of the build work for this has been done in:
- https://github.com/Storj/libstorj/pull/388
- https://github.com/Storj/libstorj/pull/366

Just need to go through the full build process and fix any issues that come up during that. And also test dylib builds.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
