### ISSUE TITLE
Windows `pread` error logging

### ISSUE THREAD

**Issue by braydonf** [Storj/libstorj#235]
`Create event failed with error:1450` from https://github.com/Storj/libstorj/blob/master/src/utils.c#L191 is being sent direct to stdout. Need to address if this error is critical, and how to handle it. See related chat at: https://community.storj.io/channel/core?msg=jpB6rAkas6gerLAk8

**Comment by aleitner** [comment]
System error
ERROR_NO_SYSTEM_RESOURCES
1450 (0x5AA)
Insufficient system resources exist to complete the requested service.

**Comment by aleitner** [comment]
We are bumping the max shard size to 4Gb and the determine_shard_size function has been refactored. Before it would limit shard size based on concurrency to limit memory usage, but now it doesn't care about memory usage. Previously I think really, really big files would cause the shard size to be 8Mb or something really low because of the old logic.
