### ISSUE TITLE
Progress updates with reed solomon for downloads and uploads

### ISSUE THREAD

**Issue by braydonf** [storj/libstorj#302]
The progress bar often times will not reach 100% because there are shards missing that are being recovered for successful download.

During uploads, there may not be indication of activity while parity shards are being encoded, adding progress callback here could give feedback.

**Comment by braydonf** [comment]
Also include more info about what "Preparing..." means.

**Comment by braydonf** [comment]
Another thing to consider is to have an additional callback for total file progress, and another callback for the actual bytes transferred.

**Comment by kaloyan-raev** [comment]
Currently the `totalBytes` value is inaccurate and it even changes (?!) during the file transfer. Hence, it can be also observed that the `progress` percentage goes backwards from time to time.

I am attaching two logs of the reported progress - one for uploading and one for downloading of a file with the size of 65,882,536 bytes.

[upload.txt](https://github.com/Storj/libstorj/files/1491046/upload.txt)
[download.txt](https://github.com/Storj/libstorj/files/1491045/download.txt)

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
