### ISSUE TITLE
Build release w/ and for debian "jessie"

### ISSUE THREAD

**Issue by braydonf** [storj/libstorj#335]
To support libc6 2.19 https://packages.debian.org/jessie/libc6

**Comment by marcolivierarsenault** [comment]
For info, 
With the help of @braydonf I successfully compiled if for Debian Jessie.

I followed the procedure for _x86_64-pc-linux-gnu_ with some added steps:

1) Need to compile libuv manually (not available on Debian Repo) from here: https://github.com/libuv/libuv 
2) Needed to add another Flag in the configure string: **-std=gnu99** (If not you get a compile error)
 `PKG_CONFIG_LIBDIR="$(pwd)/depends/build/x86_64-pc-linux-gnu/lib/pkgconfig" CFLAGS="-I$(pwd)/depends/build/x86_64-pc-linux-gnu/include -std=gnu99 -L$(pwd)/depends/build/x86_64-pc-linux-gnu/lib -static" ./configure --host=x86_64-pc-linux-gnu --enable-static --disable-shared --prefix=$(pwd)/depends/build/x86_64-pc-linux-gnu`

**Comment by bitbox** [comment]
FYI:
It's also possible to take a different approach for having the amd64 pre-compiled `libstorj-1.0.0-linux64` binary working on Debian Jessie. It involves upgrading the `kernel` and installing `libuv1-dev` from `jessie-backports`, then upgrading `libc6` from `stretch`. For those of us who can afford that luxury, probably running some sort of VM, here are the rough commands to use on a fresh Debian Jessie install:
```
> echo deb http://ftp.debian.org/debian jessie-backports main contrib >> /etc/apt/sources.list.d/backports.list`
> echo deb http://ftp.debian.org/debian stretch main >> /etc/apt/sources.list.d/stretch.list
> apt-get update
> apt-cache search linux-image
> apt-get install -t jessie-backports linux-image-amd64
> reboot
> apt-get install -t jessie libcurl4-gnutls-dev nettle-dev libjson-c-dev
> apt-get install libuv1-dev/jessie-backports
> apt-get install -t stretch libc6
    Restart services -> YES
> wget https://github.com/Storj/libstorj/releases/download/v1.0.0/libstorj-1.0.0-linux64.tar.gz
> tar xvf libstorj-1.0.0-linux64.tar.gz -C /opt/
> chown -R root:root /opt/libstorj-1.0.0
> cd /opt/libstorj-1.0.0/bin/
> ./storj --help
```
If you would like a little more verbose version you can have a look at [this wiki page of mine](http://wiki.strategicz.com/vhyper/doku.php?id=vms:storj).

Best.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
