### ISSUE TITLE
import-keys command fails

### ISSUE THREAD

**Issue by ghost** [storj/libstorj#364]
`./storj import-keys` fails with error message "Failed to write to disk". `./storj register` works fine and writes a config file to disk, so it shouldn't be permission-related

**Comment by braydonf** [comment]
What OS and release?

**Comment by braydonf** [comment]
Is there a file at `~/.storj/api.storj.io.json` and what are the permissions? (e.g. `~/.storj$ ls -alh`)

**Comment by Gasp0de** [comment]
There is now, but it contains the contents from the register command (I created a new user after trying to import my already created acount). Permissions are -rw-r--r-- for my user. I am on Arch Linux and compiled the source on the day I created this issue.

**Comment by braydonf** [comment]
`register` and `import-keys` will call `import_keys` so both are using the same method. Are there any other differences between using `register` vs `import-keys`.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
