### ISSUE TITLE
Creating buckets in app.storj.io do not show in FileZilla during bucket listing

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/libstorj#367]
```
Status:	Connecting to app.storj.io...
Status:	Retrieving directory listing...
Command:	list-buckets
Error:	Request failed with status code 302
Error:	Failed to retrieve directory listing
```

**Comment by heunland** [comment]
user @Baseminer reports a similar issue:
```Status:	Connecting to api.storj.io...
Status:	Retrieving directory listing...
Command:	list-buckets
Error:	Request failed with status code 401
Error:	Failed to retrieve directory listing```

also @JukeboxRhino
```
Command:	list-buckets
Error:	Request failed with status code 0
Trace:	CStorjListOpData::ParseResponse() in state 3
Trace:	CStorjControlSocket::ResetOperation(2)
Trace:	CControlSocket::ResetOperation(2)
Error:	Failed to retrieve directory listing
Trace:	CFileZillaEnginePrivate::ResetOperation(2)
```

**Comment by ramdasgokul** [comment]
Same issue

```
Status:      	Connecting to api.storj.io...
Status:      	Retrieving directory listing...
Command:	list-buckets
Error:        	Request failed with status code 401
Error:        	Failed to retrieve directory listing 
```

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
