### ISSUE TITLE
FileZilla compatibility issue with Windows Server 2016 on KVM virtualization platforms 

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/libstorj#373]
```
Dear Meije,

Unfortunately our technicians did not find any issue. As the problem only exists when using Storj, we strongly suspect the issue is with the (compatibility) of this program with OS and/or VPS platform. Of course this is speculation, since we found no issue. However the fact that we found no problem is a strong indication of this.

We have now exhausted our options for further investigation unless new information surfaces. Perhaps it is an option for you, to check with the Storj people if their software is fully compatible with Windows Server 2016 on KVM virtualisation platforms. 

Regards,

Marinus Verhoeven
```
https://www.transip.eu

Please inform if FileZilla with Storj is fully compatible with Windows Server 2016 on KVM virtualisation platforms. 

The result of this issue is that the Internet connection drops when downloading files (yellow triangle over the LAN tray icon). Only resetting the adapter works.

**Comment by MeijeSibbel** [comment]
```
Hello Mr. Sibbel,

I've read the quoted reply in the linked Github issue and my theory is, that the problem relies in the Storj-protocol, or, to be more precise, in how the protocol generates network traffic. I suspect it's not the consumed bandwidth that's causing the problem, as we have dozens of customers that are maxing out their bandwidth nearly 24/7. I suspect it's the package count that creates these problems in the interaction between the virtualized networking hardware and the operating system.


------
Mit freundlichen Grüßen / Best Regards
Philipp Born

myLoc managed IT AG
- Systemadministrator Cloud & Virtualized Solutions -
```

**Comment by MeijeSibbel** [comment]
This appears to be true even for dedicated servers and machines that are not virtualized on a windows server 2016 OS.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
