### ISSUE TITLE
Error:	Request failed with status code 0

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/libstorj#376]
```
Status:	Retrieving directory listing of "/8-9-2017"...
Command:	list 826d393b9ab6e03b3085e581 
Error:	Request failed with status code 0
Command:	put 826d393b9ab6e03b3085e581 "C:\Users\Administrator\Desktop\storj\A109.tmp" "A109.tmp"
Status:	File transfer successful, transferred 8,758,096,384 bytes in 3330 seconds
Status:	Starting upload of C:\Users\Administrator\Desktop\storj\A112.tmp
Status:	Retrieving directory listing of "/"...
Command:	list-buckets
Error:	Request failed with status code 0
Error:	File transfer failed
Status:	Starting upload of C:\Users\Administrator\Desktop\storj\A112.tmp
Status:	Retrieving directory listing of "/"...
Status:	Retrieving directory listing of "/8-9-2017"...
Status:	File transfer successful, transferred 8,758,096,384 bytes in 4957 seconds
Status:	Starting upload of C:\Users\Administrator\Desktop\storj\A113.tmp
Status:	Retrieving directory listing of "/8-9-2017"...
Command:	list 826d393b9ab6e03b3085e581 
Error:	Request failed with status code 0
Command:	put 826d393b9ab6e03b3085e581 "C:\Users\Administrator\Desktop\storj\A112.tmp" "A112.tmp"
Status:	File transfer successful, transferred 8,758,096,384 bytes in 4483 seconds
Status:	Starting upload of C:\Users\Administrator\Desktop\storj\A114.tmp
```

**Comment by scrummie02** [comment]
I get this in Filezilla
`Status:	Connecting to api.storj.io...
Status:	Retrieving directory listing...
Command:	list-buckets
Error:	Request failed with status code 500
Error:	Failed to retrieve directory listing`

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
