### ISSUE TITLE
Unable to Login to App.Storj.Io/FileZille Storj Site Manager Username and Password Missing

### ISSUE THREAD

**Issue by mgbvox** [storj/libstorj#378]
I'm getting the following two messages (when attempting to sign in on my iOS device and macbook pro, respectively): 1) connection 68 to bridge-db-int-1.prod.storj.io:27020 timed out, and 2) Failed to Fetch. I've checked my internet connection; I'm currently pulling 100 MBPS.

Later, I got this on my macbook: "connection 54 to bridge-db-int-2.prod.storj.io:27020 timed out"

This is all to get the username and password for the FileZilla Storj site manager login, which for whatever reason was left out of any correspondence with me (and I would assume the population at large). 

So... yeah, I'd like both issues addressed.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
