### ISSUE TITLE
Unable upload files/folders which names contains non-ASCII symbols with FileZilla in Windows

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/libstorj#383]
When i tried to upload Russian files to the bucket with FileZilla for Windows, i got a error:
```
Command:	put 1c8bf40f60a4e5d976a12d78 "Z:\Video\видео AD\модуль 14. AD LDS.MP4" "видео AD/модуль 14. AD LDS.MP4"
Error:	Could not open local file Z:\Video\видео AD\модуль 14. AD LDS.MP4 for reading: 2
Error:	File transfer failed
```
On Linux this is possible and working perfect.

**Comment by TopperDEL** [comment]
I see the same error when using filezilla together with german special characters ("Umlaute") like ä, ö, ü or ß. Seems the filenames are not allowed to contain unicode-characters.

**Comment by AlexeyALeonov** [comment]
This is related to the https://github.com/AlexeyALeonov/storj-upload/issues/3 
This problem exactly with libstorj, not with FileZilla itself

**Comment by kaloyan-raev** [comment]
The reason is in the limitations Windows has for the `fopen()` function. `_wfopen()` should be used instead - only for Windows.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
