### ISSUE TITLE
API Function for calculating HMAC for a local file

### ISSUE THREAD

**Issue by kaloyan-raev** [storj/libstorj#401]
As described in https://github.com/Storj/sips/blob/master/sip-0005.md#data-integrity-and-authenticity, before uploading a file, an HMAC value is calculated and stored with the file metadata on the bridge.

Is it possible to have an API function that just calculates the HMAC for a local file without the rest of the upload logic? The client would give the local file path and the bucket id (as if the file would be uploaded to that bucket). The function would do the sharding necessary for the HMAC calculation, but would not communicate to the bucket or to any farmer.

I need this to be able to compare if a file in a bucket is the same as the available copy on the client's local storage. The bridge would give me HMAC from the stored file meta data. This new function would calculate an HMAC for the local copy that I can compare to the one returned by the bridge.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
