### ISSUE TITLE
Failed to remove file from bucket. (0)

### ISSUE THREAD

**Issue by MeijeSibbel** [storj/libstorj#404]
```
Unlock passphrase: *********
Failed to remove file from bucket. (0)
5afd655da8e44ab4e302cab0
Unlock passphrase: *********
Failed to remove file from bucket. (0)
53c74511a4bab14060a567a4
Unlock passphrase: *********
File was successfully removed from bucket.
b56abb564aa8800460f20d3d
Unlock passphrase: *********
```

**Comment by efx** [comment]
Also seeing this with a file i just uploaded. I am using https://github.com/Storj/libstorj/releases/download/v2.0.0-beta/libstorj-2.0.0-beta-linux64.tar.gz
```sh
» ./bin/storj remove-file mybucketid  myfileid
Unlock passphrase:
Failed to remove file from bucket. (500)
```
I tried again and got: `Failed to remove file from bucket. (0)`

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
