### ISSUE TITLE
upload-file creates a file with the name containing the full path

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/libstorj#429]
```
storj upload-file bucketID /root/file.txt
storj list-files bucketID
ID: fileID Size: 1090 bytes Decrypted: true Type: application/octet-stream  Created: 2018-03-01T00:34:29.691Z Name: /root/file.txt
```

**Comment by braydonf** [comment]
Confirmed, getting the same problem.

**Comment by braydonf** [comment]
@aligeti You know if this has recently changed?

**Comment by AlexeyALeonov** [comment]
https://docs.storj.io/discuss/5a9413b395b180004898e9aa confirmed too

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
