### ISSUE TITLE
Code review of crypto.c

### ISSUE THREAD

**Issue by rot256** [storj/libstorj#434]
I  did a casual read though of the cryptography related parts of the project and discovered a few minor issues:

Wrong type at [/src/crypto.c#L431](https://github.com/Storj/libstorj/blob/master/src/crypto.c#L431)

Comparison of GCM tags is not constant time: [src/crypto.c#L415](https://github.com/Storj/libstorj/blob/master/src/crypto.c#L415)
Unlike HMAC, truncating GCM tags is disastrous (successful forgeries allows recovery of the authentication key). The use of memcmp may cause the code to be vulnerable to a similar attack,
since the attacker can theoretically leak how much of the tag successfully validated (effectively validating a truncated MAC). 
Using a constant time comparison fixes this.
For more details see: https://csrc.nist.gov/csrc/media/projects/block-cipher-techniques/documents/bcm/comments/cwc-gcm/ferguson2.pdf

Consider using #define for error codes in: [src/crypto.c#L558](https://github.com/Storj/libstorj/blob/master/src/crypto.c#L558)

I would advise against using asserts to check error conditions: [src/utils.c#L137](https://github.com/Storj/libstorj/blob/master/src/utils.c#L137)
Since these are disabled by NDEBUG.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
