### ISSUE TITLE
Request failed with status code: 404

### ISSUE THREAD

**Issue by jonatasheringer** [storj/libstorj#454]
after running command.(properly filled of course)
# storj cp -[rR] storj://<bucket-name>/ /<some-dir>/
i get error:
Request failed with status code: 404
i am able to list buckets and files, so i don't know whats the problem.
if i use download-file, the program falls into a infinite loop asking:
 Would you like to overwrite [/home//jonatas/Downloads/]: [y/n] 
it cant take my input and there is no existing file to be overwrited.

i hope i gave enogh info. its my first time reporting a problem.
thanks all developers for your efforts.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
