### ISSUE TITLE
Error: Unable to create download list file

### ISSUE THREAD

**Issue by martin-tomasek** [storj/libstorj#456]
C:\Users\Martin\Downloads\libstorj-2.0.0-beta3-win64\libstorj-2.0.0-beta3\bin>**storj ls Backup**
Unlock passphrase:
ID: **a43ecf0c61f4fd7cfade36c6**    Name: Backup
[list_files_callback][812] **Unable to create download list file**

C:\Users\Martin\Downloads\libstorj-2.0.0-beta3-win64\libstorj-2.0.0-beta3\bin>**storj list-files a43ecf0c61f4fd7cfade36c6**
Unlock passphrase:
[list_files_callback][812] **Unable to create download list file**

**Comment by martin-tomasek** [comment]
This is because c:/tmp did not exist. After creating the c:/tmp folder, it works.

https://github.com/storj/libstorj/blob/v2.0.0-beta3/src/cli_callback.c

    FILE *dwnld_list_fd = stdout;
    if ((dwnld_list_fd = fopen("/tmp/dwnld_list.txt", "w")) == NULL) {
        printf("[%s][%d] Unable to create download list file\n",
               __FUNCTION__, __LINE__);
        goto cleanup;
    }

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
